// src/components/Popups/Login.svelte
<script>
  import Input from './../Input.svelte'
  import Button from './../Button.svelte'

  let nomeUsuario = ''
  let password = ''

  const handleName = ({detail}) => {
    nomeUsuario = detail.str
  }
  const handlePassword = ({detail}) => {
    password = detail.str
  }
</script>

<div class="card">
  <h1 class="title">Bem Vindo,</h1>
  <span class="tiny-title">entre na sua conta para continuar</span>

  <div class="inputs">
    <Input placeholder="nome do usuário:" value={nomeUsuario} on:update={handleName}/>
    <Input placeholder="senha:" type="password" value={password} on:update={handlePassword}/>
  </div>
  <div class="button">
    <Button value="Continuar"/>
  </div>
</div>

<style>

.inputs {
  margin: 14px 0;
}

.button {
  width: 100%;
  display: flex;
  justify-content: center;
}

.card {
  flex-basis: 600px;
  margin: 6px;
  margin-top: 100px;
  background-color: #232222;
  border-radius: 8px;
  z-index: 50;
  padding: 50px;
}

.title {
  color: var(--blue);
  text-shadow: 0 0 1px rgba(61,111,208,.4);
  margin: 0;
}

.tiny-title {
  color: var(--white);
  font-size: 1.1em;
}

</style>

// components/Popup/Login.vue
<template>
  <div class="Login card rb" @click.stop>
    <h2 class="title">Bem vindo,</h2>
    <span class="sub-title">insira as informações para continuar.</span>
    <div style="height: 30px"></div>
    <div>
      <InputApp
        class="form"
        placeholder="Nome de usuário:"
        type="text"
      />
    </div>
    <div style="height: 10px"></div>
    <div>
      <InputApp
        class="form"
        placeholder="Senha:"
        type="text"
        :borderLine="true"
      />
    </div>
    <div style="height: 30px"></div>
    <div class="center">
      <Button class="btn" value="Venha se divertir!"/>
    </div>
  </div>
</template>

<script>

import InputVue from '../Auth/Input.vue'
import ButtonVue from '../Auth/Button.vue'

export default {
  components: {
    InputApp: InputVue,
    Button: ButtonVue,
  }  
}

</script>

<style scoped>

.center {
  display: flex;
  justify-content: center;
}

.card {
  padding: 40px;
  padding-right: 0;
  flex-basis: 450px;
  overflow: hidden;
}

.title {
  margin: 0;
  color: var(--orange);
}

.btn {
  margin-left: -30px;
}

</style>
