// components/Popup/Popup.vue
<template>
  <div class="Popup">
    <div class="card">
      {{ isPopupOpened }}
    </div>
  </div>
</template>

<script>

import { mapState, mapGetters } from 'vuex'

export default {
  created() {
    setTimeout(() => {
      this.$store.dispatch('popup/pushPopup', {comp: 'asdf'})
    }, 1000)
  },
  computed: {
    ...mapGetters({
      isPopupOpened: 'popup/isPopupOpened'
    }),
  }
}

</script>

<style scoped>

.Popup {
  position: absolute;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
}

</style>

// src/components/Popup/Popup.svelte
<script>

  export let segment
</script>

<main class="wrapper">
  <div class="card">
    <p>açslkjdfaslçfkdj asfdj </p>
    <p>açslkjdfaslçfkdj asfdj </p>
    <p>açslkjdfaslçfkdj asfdj </p>
    <p>açslkjdfaslçfkdj asfdj </p>
  </div>
</main>

<style>

.wrapper {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
}

.card {
  box-shadow: 0 6px 8px rgba(100,100,100,0.2);
  border-radius: 6px;
}

</style>
