// src/components/NavBar.svelte
<script>
  import { onMount } from 'svelte'

  export let segment

  let doc = null
  let scrollTop = 0

  $: act = (route) => segment === route
  $: isShadowMode = scrollTop > 50
  $: lineStyle = () => {
    segment
    if (doc) {
      const nav = doc.getElementsByClassName('NavBar')[0]
      const act = nav.getElementsByClassName('active')[0]
  
      return `left: ${act.offsetLeft}px;width: ${act.offsetWidth}px;`
    }
    return ''
  }

  onMount(() => {
    doc = document
    window.addEventListener('scroll', () => scrollTop = window.scrollY)
    lineStyle()
  })
</script>

<div class="NavBar" class:shadow={isShadowMode}>
  <div class="wrapper">
    <div class="logo">DEV WAY</div>
    <div class="links">
      <a href="/home" class="link" class:active={act('home')}>Home</a>
      <a href="/posts" class="link" class:active={act('posts')}>Posts</a>
      <a href="/contato" class="link" class:active={act('contato')}>Contato</a>
    </div>
    <div class="options">

    </div>
    <span class="line" style={lineStyle()}></span>
  </div>
</div>

<style>

.line {
  position: absolute;
  height: 3px;
  border-radius: 6px;
  width: 100px;
  background-color: var(--primary);
  bottom: -1.5px;
  transition: left .3s;
}

.link {
  text-decoration: none;
  padding: 0 13px;
  font-size: 1.1em;
  transition: color .3s;
}

.active, .link:hover {
  color: var(--primary);
}

.logo {
  font-size: 2.3em;
}

.wrapper {
  position: relative;
  margin: 0 150px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  height: 100%;
}

.NavBar {
  border-bottom: 1px solid var(--light-gray);
  height: 80px;
  position: fixed;
  width: 100%;
  top: 0;
  left: 0;
  transition-duration: .4s;
  background-color: white;
}

.shadow {
  height: 60px;
  box-shadow: 0 2px 4px rgba(100,100,100,.2);
  border: none;
}

</style>

// components/Navbar.vue
<template>
  <div class="NavBar">
    <div class="wrapper">
      <div class="logo">DEV WAY</div>
      <div>
        <nuxt-link class="link" to="/">Home</nuxt-link>
        <nuxt-link class="link" to="/posts">Posts</nuxt-link>
        <nuxt-link class="link" to="/contato">Contato</nuxt-link>
      </div>
      <div>açsdlfj</div>
      <div class="line"></div>
    </div>
  </div>
</template>

<script>

export default {
  mounted() {
    this.moveLine()
    window.addEventListener('resize', this.moveLine)
  },
  methods: {
    moveLine() {
      const line = document.getElementsByClassName('line')[0]
      const active = document.getElementsByClassName('nuxt-link-exact-active')[0]
      
      if (line && active) {
          line.style.width = active.offsetWidth + 'px'
          line.style.left = active.offsetLeft + 'px'
      }
    }
  },
  watch: {
    $route() {
      setTimeout(() => {
        this.moveLine()
      })
    }
  }
}

</script>

<style scoped>

.NavBar {
  border-bottom: 1px solid var(--light-gray);
  display: flex;
  align-items: center;
  background-color: white;
  position: fixed;
  height: 80px;
  width: 100%;
  left: 0;
  top: 0;
}

.logo {
  font-size: 2.2em;
}

.wrapper {
  margin: 0 100px;
  height: 100%;
  width: 100%;
  display: flex;
  justify-content: space-between;
  align-items: center;
  position: relative;
}

.link {
  text-decoration: none;
  color: rgba(100, 100, 100, .7);
  display: inline-block;
  padding: 0 24px;
  transition-duration: .3s;
  font-size: 1.1em;
}

.line {
  position: absolute;
  bottom: -2px;
  height: 3px;
  width: 100px;
  border-radius: 3px;
  background-color: var(--orange);
  transition-duration: .2s;
}

.nuxt-link-exact-active, .link:hover {
  color: var(--orange);
}

</style>
